function fds = p68_fds_init
%
%  P68_FDS_INIT  Initializes a standard data structure for the P.68 aircraft.  
%
%  Usage: fds = p68_fds_init;
%
%  Description:
%
%    Initializes the flight data structure 
%    for the F-16, in SIDPAC standard format.  
%    All data fields are initialized to an 
%    empty matrix, except for parameters that 
%    can be set specifically for the P.68.  
%
%  Input:
%    
%    None
%
%  Output:
%
%    fds = flight data structure in standard configuration.
%

%
%    Calls:
%      p68_props.m
%
%    Author:  Eugene A. Morelli
%
%    History:  
%      27 Feb 2010 - Created and debugged, EAM.
%      03 Sep 2013 - Updated for consistency, EAM.
%      25 Nov 2014 - Updated units for consistency, EAM.
%      23 Jul 2015 - Added body axis velocity components, 
%                    ps, ta, and re-arranged lat and lon, EAM.
%
%  Copyright (C) Eugene A. Morelli
%
%  This software and/or technical data carry no warranty 
%  of any kind, either expressed, implied, or statutory. 
%
%  Please email bug reports or suggestions for improvements to:
%
%      e.a.morelli@nasa.gov
%

%
%  Initialize the flight data structure (fds).  
%
fds=struct('t',[],...
           'fdata',[]);
%
%  Experiment information.
%
fds.aircraft='p68';
fds.maneuver=[];
fds.test_date=[];
fds.pilot=[];
%
%  Default variable descriptions.
%
fds.vardesc={'  time  (s) ';...
             '  airspeed  (ft/s) ';...
             '  sideslip angle  (deg) ';...
             '  angle of attack  (deg) ';...
             '  roll rate  (deg/s) ';...
             '  pitch rate  (deg/s) ';...
             '  yaw rate  (deg/s) ';...
             '  roll angle  (deg) ';...
             '  pitch angle  (deg) ';...
             '  heading angle  (deg) ';...
             '  ax  (g) ';...
             '  ay  (g) ';...
             '  az  (g) ';...
             '  stabilator  (deg) ';...
             '  aileron  (deg) ';...
             '  rudder  (deg) ';...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             '  dynamic pressure  (lbf/ft2) ';...
             '  mach number ';...
             '  air density  (slug/ft3) ';...
             '  altitude  (ft) ';...
             '  lon stick ';...
             '  lat stick ';...
             '  rdr pedal ';...
             '  throttle ';...
             [];...
             '  power level  (percent) ';...
             [];...
             '  thrust  (lbf) ';...
             [];...
             '  engine rpm  (rev/min) ';...
             [];...
             '  roll accel  (deg/s2) ';...
             '  pitch accel  (deg/s2) ';...
             '  yaw accel  (deg/s2) ';...
             '  x cg position  (in) ';...
             '  y cg position  (in) ';...
             '  z cg position  (in) ';...
             '  mass  (slug) ';...
             '  Ixx  (slug-ft2) ';...
             '  Iyy  (slug-ft2) ';...
             '  Izz  (slug-ft2) ';...
             '  Ixz  (slug-ft2) ';...
             '  measured roll rate  (deg/s) ';...
             '  measured pitch rate  (deg/s) ';...
             '  measured yaw rate  (deg/s) ';...
             '  measured ax  (g) ';...
             '  measured ay  (g) ';...
             '  measured az  (g) ';...
             '  beta dot  (deg/s) ';...
             '  alpha dot  (deg/s) ';...
             '  CX ';...
             '  CY ';...
             '  CZ ';...
             '  C1 ';...
             '  Cm ';...
             '  Cn ';...
             '  CD ';...
             '  CYw ';...
             '  CL ';...
             '  CT ';...
             '  phat ';...
             '  qhat ';...
             '  rhat ';...
             '  u  (ft/s) ';...
             '  v  (ft/s) ';...
             '  w  (ft/s) ';...
             '  wing area  (ft2) ';...
             '  wing span  (ft) ';...
             '  wing mac  (ft) ';...
             '  meas sideslip angle  (deg) ';...
             '  meas angle of attack  (deg) ';...
             [];...
             [];...
             '  latitude  (deg) ';...
             '  longitude  (deg) ';...
             [];...
             [];...
             [];...
             '  static pressure  (lbf/ft2) ';...
             '  ambient temperature  (deg F) '};
%
%  Default variable labels.
%
fds.varlab={'  time ';...
            '  vt ';...
            '  beta ';...
            '  alpha ';...
            '  p ';...
            '  q ';...
            '  r ';...
            '  phi ';...
            '  the ';...
            '  psi ';...
            '  ax ';...
            '  ay ';...
            '  az ';...
            '  stab ';...
            '  ail ';...
            '  rdr ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '  qbar ';...
            '  mach ';...
            '  rho ';...
            '  alt ';...
            '  lonstk ';...
            '  latstk ';...
            '  rudped ';...
            '  thtl ';...
            '      ';...
            '  pwr ';...
            '      ';...
            '  thrust ';...
            '      ';...
            '  engrpm ';...
            '      ';...
            '  pdot ';...
            '  qdot ';...
            '  rdot ';...
            '  xcg ';...
            '  ycg ';...
            '  zcg ';...
            '  mass ';...
            '  Ixx ';...
            '  Iyy ';...
            '  Izz ';...
            '  Ixz ';...
            '  pm ';...
            '  qm ';...
            '  rm ';...
            '  axm ';...
            '  aym ';...
            '  azm ';...
            '  betadot ';...
            '  alphadot ';...
            '  CX ';...
            '  CY ';...
            '  CZ ';...
            '  C1 ';...
            '  Cm ';...
            '  Cn ';...
            '  CD ';...
            '  CYw ';...
            '  CL ';...
            '  CT ';...
            '  phat ';...
            '  qhat ';...
            '  rhat ';...
            '  u ';...
            '  v ';...
            '  w ';...
            '  sarea ';...
            '  bspan ';...
            '  cbar ';...
            '  betam ';...
            '  alpham ';...
            '      ';...
            '      ';...
            '  lat ';...
            '  lon ';...
            '      ';...
            '      ';...
            '      ';...
            '  ps ';...
            '  ta '};
%
%  Default variable units.
%
fds.varunits={' (s) ';...
              ' (ft/s) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (deg/s) ';...
              ' (deg/s) ';...
              ' (deg/s) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (g) ';...
              ' (g) ';...
              ' (g) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (deg) ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              ' (lbf/ft2) ';...
              '   ';...
              ' (slug/ft3) ';...
              ' (ft) ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              ' (percent) ';...
              '   ';...
              ' (lbf) ';...
              '   ';...
              ' (rev/min) ';...
              '   ';...
              ' (deg/s2) ';...
              ' (deg/s2) ';...
              ' (deg/s2) ';...
              ' (in) ';...
              ' (in) ';...
              ' (in) ';...
              ' (slug) ';...
              ' (slug-ft2) ';...
              ' (slug-ft2) ';...
              ' (slug-ft2) ';...
              ' (slug-ft2) ';...
              ' (deg/s) ';...
              ' (deg/s) ';...
              ' (deg/s) ';...
              ' (g) ';...
              ' (g) ';...
              ' (g) ';...
              ' (deg/s) ';...
              ' (deg/s) ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              ' (ft/s) ';...
              ' (ft/s) ';...
              ' (ft/s) ';...
              ' (ft2) ';...
              ' (ft) ';...
              ' (ft) ';...
              ' (deg) ';...
              ' (deg) ';...
              '   ';...
              '   ';...
              ' (deg) ';...
              ' (deg) ';...
              '   ';...
              '   ';...
              '   ';...
              ' (lbf/ft2) ';...
              ' (deg F) '};
%
%  Aircraft wing geometry.
%
c=p68_props;
fds.sarea=c.sarea;
fds.bspan=c.bspan;
fds.cbar=c.cbar;
%
%  User notes.
%
fds.notes=[];
%
%  Record when fds was created.
%
fds.created=datestr(now);
return
